name: Java CI with Gradle
on:
  push:
    branches: [ "feat/cicd" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      HOSTNAME: ${{secrets.EC2_SSH_HOST}}
      USER_NAME: ${{secrets.EC2_USER_NAME}}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Check dir
        run: pwd && ls

      - name: Build
        working-directory: ./kiwoyu
        run: |
          ./gradlew build
          cp build/libs/kiwoyu-0.0.1-SNAPSHOT.jar ../

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: kiwoyu_jar
          path: kiwoyu/build/libs/kiwoyu-0.0.1-SNAPSHOT.jar
          retention-days: 1

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "kiwoyu-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/app/"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            whoami
            cd /home/ubuntu/app/scripts && ./start.sh
